### ISSUE TITLE
RPEmotes

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [AlexRXWindy/alx_emotes#1]
Dear Alex,

I trust this message finds you in good health.

Acknowledging your concerns regarding the outdated design of RPEmotes, I wish to emphasize that our project thrives on community involvement, welcoming pull requests, suggestions, and collaborations with various animation and prop creators.

Should you find dissatisfaction with the appearance of RPEmotes or the dpemotes menu, we extend a warm invitation to join our Discord, providing an opportunity to engage in a discussion with our dedicated Development team.

It has come to my attention that there are differing opinions on the consistency of the RPEmotes repository's license, and I concur that certain clauses may be subject to scrutiny. While I recognize the importance of seeking permission for contributions based on others' work, it's pertinent to note that RPEmotes has obtained authorization from relevant creators.

Your recent post has been reported, and it's imperative to understand that all free releases on the forums must include a direct upload or GitHub link for compliance.

Conversations have transpired with individuals whom I have collaborated with, and the expressions conveyed suggest a level of discontent that surpasses mere dissatisfaction. I would like to bring to your attention that ongoing discussions with Tebex staff are underway. I strongly advise reconsidering the content on your store, as, regrettably, the necessary permissions are not in place.

While the creation of an emote menu is certainly acceptable, I recommend utilizing only Rockstar Games animations and seeking explicit permission from the multiple prop and animation creators. Together, we have invested significant effort in crafting these files and coding them for the benefit of our community, with the expectation that others, including yourself, would engage in ethical practices rather than resorting to what appears to be an act of appropriation.

Sincerely,

Tay McKenzie 
Project Manager
RPEmotes

**Comment by TayMcKenzieNZ** [comment]
You have 24 hours to delete it.

**Comment by Griefa** [comment]
> You have 24 hours to delete it.

Its been longer than 24 hours

**Comment by TayMcKenzieNZ** [comment]
Fuck up cunt.
